import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "ru";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved === "ru" || saved === "en" ? saved : "en") as Language;
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];

    for (const k of keys) {
      value = value?.[k];
    }

    return typeof value === "string" ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

const translations = {
en: {
  name: "Yana Poymanova",
  nav: {
    home: "Home",
    about: "About",
    portfolio: "Portfolio",
    contact: "Contact",
  },
  home: {
    badge: "Design. Optimization. AI.",
    hero_title_1: "Senior designer",
    hero_title_2: "& AI Creator",
    hero_subtitle: "Вuild AI-powered workflows and lead creative projects end-to-end – from brief to launch. Trusted by Sber, Moscow Transport, SberTroika, Soyuzmultfilm, and Plekhanov University.",
    view_portfolio: "View Portfolio",
    get_in_touch: "Get In Touch",
    what_i_do: "What I Do",
    graphic_design: "Project management",
    graphic_design_desc: "Lead projects from the first brief to the final handoff – building clear processes for clients and teams: guides, briefs, and standards that actually get used.",
    ai_art: "AI & automation",
    ai_art_desc: "Building RAG bot on n8n with DeepSeek, Mistral, and a 20,000-product knowledge base. Integrate LLMs via API, generate content with AI (Kling, Recraft, Stable Diffusion and more).",
    creative_direction: "Creative producing",
    creative_direction_desc: "Thrive on bold, unexpected projects – and I'm hands-on all the way. Once sent a transport card to low Earth orbit. What's your next big idea?",
    featured_works: "Featured Works",
    view_all: "View All",
    cta_title: "Let's create something together!",
    cta_subtitle: "Whether it's AI integration, creative direction, or something else — I'm in. Lets’s talk!",
    start_project: "Send message",
    abstract_dreams: "Zefirka AI",
    pastel_gradients: "Troika Card in Regions",
    neon_visions: "Exclusive Album for SPIEF",
    ai_art_cat: "AI",
    digital_art_cat: "Branding",
    ai_generated_cat: "Troika Cards",
  },
  about: {
    title: "About Me",
    intro_1: "I started as a designer, but making banners wasn't enough. Design, I learned early, is never just a picture: it's a part of a product, a process, a system.",
    intro_2: "At SberTroika I supported large-scale projects and built design workflows from the ground up. I've explored different industries: education, transport, IT, and managed teams of up to 10 people along the way.",
    intro_3: "Right now, my focus is AI. I'm building an AI Telegram bot on n8n, integrating language models into real business workflows, and figuring out what actually works.",
    values_title: "What I'm Looking For",
    innovation: "Design projects",
    innovation_desc: "Ready for 360° project work: concept, design, production",
    passion: "Working with AI",
    passion_desc: "Want to integrate AI into workflows that genuinely need it.",
    excellence: "Flexible schedule",
    excellence_desc: "Open to project-based work or full-time remote. Registered as self-employed.",
    skills_title: "Skills & Tools",
    education_title: "Education",
     education_company: "Crimean Federal University ",
     education_position: "Graphic artist",
     education_desc: "Specialist degree — Graphic Art, Book Graphics & Print Design.",
    experience_title: "Experience",
      present: "Present",
      manager_position: "Lead of Design Projects",
      manager_company: "SberTroika",
      manager_desc: "Built and optimized design workflows. Led visual development for transport projects across 30+ regions. Created visual concepts for special projects. Created card collections, developed brand guidelines, and designed over 75 unique Troika card layouts.",
      senior_position: "Deputy Director of Media Center",
      senior_company: "Plekhanov University",
      senior_desc: "Developed brand identity for professional education programs: corporate style, print and exhibition materials. Promoted courses and MBA programs across social media.",
      designer_position: "Head of Design & SMM Department",
      designer_company: "Crimean Federal University",
      designer_desc: "Led the university's visual identity and admissions campaign. Built a media production workflow from scratch: video, photography, photo archive, and social media presence.",
      junior_position: "Designer",
      junior_company: "Crimean Federal University",
      junior_desc: "Print design, outdoor advertising, POS materials, and social media content.",
    },
    portfolio: {
      title: "Portfolio",
      subtitle: "A collection of my recent work in graphic design, AI art, and creative direction",
      all_work: "All Work",
      ai_art: "AI works",
      branding: "Branding",
      illustration: "Illustration",
      typography: "Troika cards",
      no_projects: "No projects found in this category.",
      project_1_title: "Zefirka AI Beauty Bot",
      project_1_desc: "AI assistant project in Telegram bot interface",
      project_1_full: "Zefirka is a smart AI beauty assistant inside Telegram. It recommends real cosmetics based on your preferences, budget, and skin type. Drawing from a database of over 20,000 products with real prices. **My role** Co-founder. Led concept development, brand creation, customer journey design, and bot logic architecture.",
      project_1_challenge_1: "The idea came from a real life: researching beauty products took too long, and generic AI tools kept recommending things unavailable in my country.",
      project_1_challenge_2: "The challenge was to build something actually useful – not just another chatbot.",
      project_1_solution_1: "Create a beauty assistant in a simple, familiar Telegram interface and LLMs integration. At the heart of the brand: Zefirka, a cat mascot with a calm expert tone.",
      project_1_solution_2: "Successfully completed beta testing with 150+ unique users, now operating on a paid subscription model.",
      project_1_roadmap_1_title: "Bot architecture",
      project_1_roadmap_1_desc: "Mapped the full customer journey and bot logic. Designed bot architecture on n8n core scenarios: product search, ingredient analysis, beauty box assembly.",
      project_1_roadmap_2_title: "Brand creation",
      project_1_roadmap_2_desc: "Researched the target audience and their real needs. Created and a character with a clear philosophy and tone of voice cartoonish enough to feel warm and be memorable.",
      project_1_roadmap_3_title: "AI integration",
      project_1_roadmap_3_desc: "Implemented DeepSeek and Mistral via LLM API. Built a RAG vector database with 20,000+ products and average market prices. Handled prompt engineering for n8n AI client.",
      project_1_roadmap_4_title: "Beta testing",
      project_1_roadmap_4_desc: "Tested functionality, collected feedback, refined the CJM. Launched on social media, ran barter collaborations with micro-creators, and bought targeted ad placements.",
      project_2_title: "Troika Card regional design",
      project_2_desc: "Creating cards design as a symbol of regional identity.",
      project_2_full: "Troika is Moscow's iconic transport card. Today it works across 20+ regions of Russia, and each region gets its own unique card design reflecting local history, nature, and culture. From 2023 to 2025, I led the full design process for regional Troika cards at SberTroika.**My role** Art direction, design process management, illustration, and client communication.",
      project_2_challenge_1: "Every new design project started without a system – no guidelines, no briefs, no documentation.",
      project_2_challenge_2: "Every project involved balancing three sets of expectations: the company's requirements, the region's vision, and the approval of the Troika brand owner.",
      project_2_solution_1: "The solution: built a structured design workflow with clear stages and realistic deadlines. Created a unified client brief, a design guideline covering visual rules, and a standardized presentation template.",
      project_2_solution_2: "The result: approval time dropped by 20%, about 80% of projects approved on first try with minimal revisions. Over 75 card designs created; more than 25 released as part of the regional Troika series. Only in 2025 over 65,000 cards printed.",
      project_2_roadmap_1_title: "Brief development",
      project_2_roadmap_1_desc: "Built an online brief for external clients with questions about preferences, color palettes, and deadlines. Completed briefs were automatically distributed to all project stakeholders.",
      project_2_roadmap_2_title: "Guideline creation",
      project_2_roadmap_2_desc: "Developed a guide covering the full design timeline and all visual requirements – combining the Troika brand book with internal rules.",
      project_2_roadmap_3_title: "Client collaboration",
      project_2_roadmap_3_desc: "Designs went through three approval rounds (company management → region → brand owner). The brief and guideline smoothed the process; Figma Team presentation templates made reviews faster.",
      project_2_roadmap_4_title: "Design research",
      project_2_roadmap_4_desc: "Each project began with deep research into the region — its traditions, landmarks, and the local identity. At concept stage: 3–5 ideas proposed, 2–3 taken to full render. Final deliverable: at least 2 polished layouts, hand-drawn in Adobe Illustrator or Procreate.",
      project_3_title: "Design System for Transport Materials",
      project_3_desc: "Creating a system of design materials for launching regional transport projects at SberTroika",
      project_3_full: "Over 17,000 passenger transport connected to the SberTroika ticketing system across 34 regions — and every one of them carries informational materials that passengers rely on daily. To ensure consistent quality, I built a unified system for preparing printed and digital materials. **My role** Art direction, design process architecture, and hands-on design development.",
      project_3_challenge_1: "Tens of thousands of stickers and leaflets were printed every year — but without a system. ",
      project_3_challenge_2: "Layouts looked similar on the surface, yet each region had its own variations, leading to constant reprints.",
      project_3_solution_1: "The solution: created a modular starter pack that covers most regional needs out of the box — or can be quickly adapted. Developed a guideline for all material types with usage instructions. ",
      project_3_solution_2: "The result: released over 10,000 new materials. The audit identified projects needing urgent updates — addressing a backlog that had built up over years.",
      project_3_roadmap_1_title: "Material audit",
      project_3_roadmap_1_desc: "Analyzed and catalogued all existing layouts. Identified the most-used formats and flagged outdated materials in coordination with regional managers.",
      project_3_roadmap_2_title: "Brief & guideline",
      project_3_roadmap_2_desc: "Prepared a client brief for collecting needs and deadlines. Built a guideline with base and extended packages covering 70% of regional requirements.",
      project_4_title: "Troika Card in Space",
      project_4_desc: "A transport card that made it to low Earth orbit.",
      project_4_full: "A transport card created as a joint project between SberTroika and the Space-π educational initiative, became the first transport card ever launched into orbit. Its design features a drawing by a child from the programme's competition. A series of five cards was released, each exploring space through children's eyes. **My role** Art direction.",
      project_4_challenge_1: "Goal: raise brand awareness for Troika, and draw public attention to an educational project helping schoolchildren participate in real space research.",
      project_4_challenge_2: "Project had social significance and was done on a charitable basis with support from the Innovation Promotion Fund.",
      project_4_solution_1: "The solution: created a series of designs featuring digitized children's drawings from competition finalists. Each one focused on space and environmental themes.",
      project_4_solution_2: "The result: the unifying character across all five cards is an octopus: the official mascot of the Space-π project. The result is a collectible series that tells a story, not just fills a wallet.",
      project_5_title: "Troika Card × Local Culture",
      project_5_desc: "Promote the Troika card & local cultural tourism",
      project_5_full: "'Travel with Troika in the Moscow Region' was a collaborative campaign between SberTroika and the regional Ministry of Culture and Tourism. It combined a limited-edition card design with a museum activation campaign – using the Troika card as a travel tool, not just a transit card. **My role** Art direction.",
      project_5_challenge_1: "Two goals in one project: increase Troika card usage in the region, and promote domestic cultural tourism.",
      project_5_challenge_2: "The card needed to do more than look good – it had to carry a campaign concept.",
      project_5_solution_1: "The solution: the campaign mechanic: visit a museum, find the activation, post on social media. The card design concept: a map within a map — each cultural site embedded in the card layout.",
      project_5_solution_2: "The result: campaign launched across 5 museums in autumn. Wide media coverage from day one. In the first two weeks: 500+ participants posting with special promotion hashteg.",
      project_5_roadmap_1_title: "Concept",
      project_5_roadmap_1_desc: "The campaign mechanic: visit a museum, find the activation, post on social media. The card design concept: a map within a map – each cultural site embedded in the card layout.",
      project_5_roadmap_2_title: "Design",
      project_5_roadmap_2_desc: "At final approval, the Troika brand owner rejected the original design. Developed a full replacement in a compressed timeline: new colour palette, new visual language, all sites preserved without cluttering the small card format.",
      project_6_title: "SberTroika × Soyuzmultfilm",
      project_6_desc: "The large design project with licensed products",
      project_6_full: "A collaboration between SberTroika and Soyuzmultfilm – the studio behind some of the most beloved Soviet animated films. The project featured characters from cartoons that have been part of Russian childhood for generations. Over the course of the collaboration, four card series were created, with more than 20,000 cards printed. **My role** Art direction, design development.",
      project_6_challenge_1: "The problem: working with licensed characters meant strict guidelines, multiple approval rounds, and no room for shortcuts.",
      project_6_challenge_2: "The challenge: meet every requirement while still creating something that felt alive and collectible — not just technically compliant.",
      project_6_solution_1: "The solution: for each cartoon, developed a series of 4–6 cards with a consistent visual style across the collection.",
      project_6_solution_2: "The result: first series was selected as a finalist at the Russia Licensing Awards. 20+ card designs created. Over 20,000 cards printed and sold at different regions, card awareness grew by an average of 5–7%.",
      project_6_roadmap_1_title: "Research",
      project_6_roadmap_1_desc: "The best research of my career: watching Soviet cartoons to identify key scenes and capture each character's personality. Critical step: studying the guidelines for each franchise (approved pairings, allowed poses, restricted elements).",
      project_6_roadmap_2_title: "Design",
      project_6_roadmap_2_desc: "Main challenge: fitting bright, detailed characters into a small card format without losing their expressiveness. Backgrounds and decorative elements gave room for creative input within the licensed constraints.",
      project_7_title: "Exclusive Album for SPIEF",
      project_7_desc: "Developing a gift for VIP guests of SPIEF",
      project_7_full: "An exclusive album with a limited-edition series of Troika cards, created for VIP guests of the St. Petersburg International Economic Forum. The album reframed what a corporate gift can be: not a souvenir that gets forgotten, but an object that tells the company's story and earns a place on the desk. Two editions were developed (2023 and 2025), each with its own concept. **My role** Concept creation, design development.",
      project_7_challenge_1: "The task wasn't just to make something beautiful – it was to create an object that communicates SberTroika's technological ambition to regional leaders and key partners.",
      project_7_solution_1: "The solution: each album told the story of a new stage in the company's work: from app launch to ticketing system rolling out in million-plus cities.",
      project_7_solution_2: "The result: first edition: 50 copies. Second: 100. Both presented at the Moscow Transport stand and gifted to key partners and regional officials.",
      project_7_roadmap_1_title: "First album (2023)",
      project_7_roadmap_1_desc: "A series dedicated to the future of transport, created in collaboration with the Kandinsky 2.1 AI. Troika underground, overground, on water, and in the air. Doubled as an announcement for the 'My Troika' app designs available as virtual cards.",
      project_7_roadmap_2_title: "Second album (2025)",
      project_7_roadmap_2_desc: "Focus on Troika's regional expansion. A series of transparent plastic cards representing the largest connected regions. The album itself featured built-in LED lighting that illuminated the cards from within.",
      project_8_title: "Novosibirsk: Transport Reform",
      project_8_desc: "Design support for a project in a one of Russia's largest cities",
      project_8_full: "In 2025, SberTroika launched a large-scale transport project in Novosibirsk, one of Russia's largest cities. The project required an extensive information campaign to guide passengers through a new ticketing system. **My role** Full design support for the project, leading design processes.",
      project_8_challenge_1: "Main task: help residents understand and trust the new system. It need non-standard layouts: completely new formats and a lot of print materials.",
      project_8_solution_1: "The solution: designed a multi-wave information campaign covering every passenger touchpoint: social media cards, website instructions, leaflets, institutional posters.", 
      project_8_solution_2: "Total scope: 200+ layouts designed, 90,000+ materials printed. 90% of the city's public transport carries the new materials. Solved large print run issue by optimizing text – cut about 40%, reducing printing costs by 20%.", 
      project_8_roadmap_1_title: "Preparation",
      project_8_roadmap_1_desc: "Developed a separate visual style, a website page, and a Telegram channel for daily updates. Updated social transport card designs for different user categories.",
      project_8_roadmap_2_title: "Design",
      project_8_roadmap_2_desc: "Created over 15 user guides and over 30 new printed materials about the transition to the new system. Released over 20 transport card designs. Designed navigation for workplace design, and workers uniform.",
      project_9_title: "The Book ‘I Draw the Sea’",
      project_9_desc: "Create the child book with original illustrations",
      project_9_full: "‘I Draw the Sea’ is a children's poetry collection published to mark the 90th birthday of Vladimir Orlov, a beloved Russian children's poet. The goal: introduce his work to a new generation of readers. The book pairs illustrated poems with interactive developmental activities for preschool-age children. **My role** Concept, illustration, layout design, and development of all educational activities.",
      project_9_challenge_1: "This was my graduation project, which meant full creative ownership and full creative responsibility.",
      project_9_challenge_2: "The brief I set for myself: create a publication with a distinct concept, useful for its audience.",      
      project_9_solution_1: "The solution: an interactive collection built around the feeling of a summer trip to the sea. Each spread pairs a poem with a full-page illustration and a flap that opens to reveal a preschool activity.",
      project_9_solution_2: "The result: 14 illustrated spreads. Published with a grant from the Ministry of Culture of the Republic of Crimea; print run of 1,000 copies.",
      project_9_roadmap_1_title: "Research & concept",
      project_9_roadmap_1_desc: "Vladimir Orlov is sometimes called the 'Crimean Marshak' – his work is closely tied to the Artek camp and the Crimean coast. That became the collection's backbone: a journey through Crimea.",
      project_9_roadmap_2_title: "Design",
      project_9_roadmap_2_desc: "The colour palette evolves through the book – dawn tones at the opening, bright midday colours in the middle, muted evening hues at the close. Each spread features a hand-illustrated poem in Adobe Photoshop, laid out in Adobe InDesign.",
      project_9_roadmap_3_title: "Learn & layout",
      project_9_roadmap_3_desc: "The flap structure physically separates the reading experience from the activity — so parents and children can engage with each at their own pace. The activities were developed in consultation with early childhood development specialists. ",
      challenges_title: "Challenges & Goals",
      solution_title: "Solution & Result",
      projectroadmap_title: "Roadmap",
      tools_title: "Tools & Technologies",
      view_project: "View more",
    },
  contact: {
    title: "Let's create something together!",
    subtitle: "Got a project? Need AI integration or project support? Let's talk.",
    get_in_touch: "Get In Touch",
    email: "Email",
    phone: "Phone",
    location: "Location",
    location_city: "Moscow",
    location_country: "Russia",
    response_time: "Response Time",
    response_desc: "I usually respond within 24 hours. For urgent projects, please mention it in your message.",
    name: "Name",
    name_placeholder: "Your name",
    email_placeholder: "your.email@example.com",
    subject: "Subject",
    subject_placeholder: "What's this about?",
    message: "Message",
    message_placeholder: "Tell me about your project...",
    send_message: "Send Message",
    thank_you: "Thank You!",
    success_message: "Your message has been sent. I'll get back to you soon.",
  },
  footer: {
    tagline: "Digital Producer & AI Creator — creating products that work.",
    quick_links: "Quick Links",
    connect: "Connect",
    copyright: "© 2026 Yana Poymanova. All rights reserved.",
  },
  },
ru: {
  name: "Яна Пойманова",
  nav: {
    home: "Главная",
    about: "Опыт",
    portfolio: "Портфолио",
    contact: "Контакты",
  },
  home: {
    badge: "Дизайн. Оптимизация. AI.",
    hero_title_1: "Senior designer",
    hero_title_2: "и AI-креатор",
    hero_subtitle: "Выстраиваю процессы, внедряю AI и\u00A0веду проекты от\u00A0идеи до\u00A0запуска. Работала с\u00A0Московским транспортом, Сбером, Союзмультфильмом и\u00A0другими.",
    view_portfolio: "Смотреть портфолио",
    get_in_touch: "Связаться",
    what_i_do: "Чем занимаюсь",
    graphic_design: "Управление дизайн-проектами",
    graphic_design_desc: "Веду проект от\u00A0брифа до\u00A0финального решения. Выстраиваю процессы – с\u00A0заказчиком и\u00A0внутри команды: гайды, брифы, стандарты.",
    ai_art: "AI и\u00A0автоматизация",
    ai_art_desc: "Создала и\u00A0развиваю RAG-бота на\u00A0n8n. Интегрирую LLM через API, генерирую контент в\u00A0нейросетях (Kling, Recraft, Claude и\u00A0не\u00A0только).",
    creative_direction: "Креативное продюсирование",
    creative_direction_desc: "Люблю нестандартные задачи и\u00A0умею быть «играющим тренером». Однажды отправила карту «Тройка» на\u00A0орбиту. Что у\u00A0вас?",
    featured_works: "Избранные работы",
    view_all: "Смотреть все",
    cta_title: "Сделаем что-нибудь классное вместе!",
    cta_subtitle: "Есть проект? AI-интеграция, дизайн или\u00A0что-то, чему вы ещё не\u00A0придумали название – пишите, разберёмся вместе.",
    start_project: "Написать",
    abstract_dreams: "Бьюти-бот Зефирка AI",
    pastel_gradients: "Карта «Тройка» в\u00A0регионах",
    neon_visions: "Эксклюзивный альбом для\u00A0ПМЭФ",
    ai_art_cat: "Работа с\u00A0AI",
    digital_art_cat: "Брендинг",
    ai_generated_cat: "Карты «Тройка»",
  },
  about: {
    title: "О себе",
    intro_1: "Начинала как дизайнер, но\u00A0быстро поняла: мне мало просто делать макеты. В IT-компании «СберТройка» я\u00A0выстраивала дизайн-процессы с\u00A0нуля и\u00A0сопровождала большие запуски. Для\u00A0меня дизайн — часть продукта, а\u00A0не\u00A0просто картинка.",
    intro_2: "Люблю глубоко погружаться в\u00A0новое: транспорт, IT, образование – каждый раз открываешь новый мир. Есть опыт управления командами до\u00A010 человек.",
    intro_3: "Сейчас мой фокус — работа с\u00A0AI-проектами. Развиваю бота на\u00A0n8n, делаю нейроконтент, интегрирую AI в\u00A0рабочие процессы.",
    values_title: "Что я ищу",
    innovation: "Управление процессами",
    innovation_desc: "Готова к\u00A0комплексной работе: от\u00A0брифа до\u00A0сдачи. Мне\u00A0комфортно отвечать за\u00A0весь проект целиком.",
    passion: "Работа с\u00A0AI",
    passion_desc: "Хочу внедрять нейросети там, где это\u00A0реально нужно и\u00A0создавать новые AI-проекты.",
    excellence: "Гибкий формат",
    excellence_desc: "Открыта к\u00A0проектной работе или\u00A0к\u00A0фулл-тайм удаленно. Оформлена как самозанятая.",
    skills_title: "Навыки и\u00A0инструменты",
    education_title: "Образование",
     education_company: "Крымский федеральный университет им.\u00A0В.И\u00A0Вернадского",
     education_position: "Художник-график (дизайн печатной продукции)",
     education_desc: "Кафедра книжной графики и\u00A0дизайна печатной продукции. Специалитет.",
    experience_title: "Опыт работы",
    present: "Настоящее время",
      manager_position: "Руководитель проектов по\u00A0дизайну",
      manager_company: "СберТройка",
      manager_desc:  "Выстраивала и\u00A0оптимизировала дизайн-процессы. Вела визуальное сопровождение транспортных проектов в\u00A034 регионах. Создала гайдлайны, обновила фирменный стиль. Разработала более 75 дизайнов карты «Тройка» – включая серию, которая побывала на\u00A0орбите.",
      senior_position: "Заместитель директора Медиацентра ДПО",
      senior_company: "РЭУ им. Г.В. Плеханова",
      senior_desc: "Развивала бренд программ допобразования: фирменный стиль, рекламные и\u00A0выставочные материалы. Продвигала курсы и\u00A0MBA-программы в\u00A0соцсетях.",
      designer_position: "Руководитель отдела Дизайна и\u00A0SMM",
      designer_company: "КФУ им. В. И. Вернадского",
      designer_desc: "Разработала визуальную концепцию вступительной кампании. Продюсировала имиджевые ролики и\u00A0фотосессии, создала фотобанк. Запустила и\u00A0развивала соцсети университета.",
      junior_position: "Дизайнер",
      junior_company: "КФУ им. В. И. Вернадского",
      junior_desc: "Создавала дизайн печатной продукции, наружной рекламы и\u00A0POS-материалов, контент для\u00A0соцсетей.",
    },
    portfolio: {
      title: "Портфолио",
      subtitle: "Подборка моих недавних работ: арт-дирекшн, брендинг, графический\u00A0дизайн,\u00A0AI.",
      all_work: "Все работы",
      ai_art: "Работа с\u00A0AI",
      branding: "Брендинг",
      illustration: "Иллюстрация",
      typography: "Карты «Тройка»",
      no_projects: "Проектов в\u00A0этой категории не\u00A0найдено.",
      project_1_title: "Бьюти-бот Зефирка\u00A0AI",
      project_1_desc: "Разработка ИИ-помощника в\u00A0интерфейсе Telegram",
      project_1_full: "Зефирка ИИ – умный бьюти-помощник в\u00A0Telegram. Подбирает реальную косметику под\u00A0предпочтения, бюджет и\u00A0тип кожи, опираясь на\u00A0базу более 20 000 товаров с\u00A0актуальными ценами. **Моя роль** Со-основатель. Концепция, создание бренда, разработка клиентского пути и\u00A0логики бота.",
      project_1_challenge_1: "Проект вырос из\u00A0личного триггера: изучать бьюти-рынок долго, а\u00A0стандартные ИИ-клиенты давали размытые советы с\u00A0товарами, которых не\u00A0найдёшь в\u00A0России.",
      project_1_challenge_2: "Персональный вызов: создать проект, который поможет сократить время на\u00A0поиск нужной косметики.",
      project_1_solution_1: "Решение: бьюти-помощник в\u00A0привычном интерфейсе Telegram. В центре бренда - кошечка Зефирка: мягкая, но\u00A0экспертная, с\u00A0чётким tone of voice, прописанным прямо в\u00A0промте. Архитектура бота собрана на\u00A0n8n, взаимодействует с\u00A0LLM и\u00A0векторным хранилищем через RAG.",
      project_1_solution_2: "Результат: более 150 уникальных пользователей за\u00A0бету. Сейчас проект работает на\u00A0платной подписке. Создали сайт на\u00A0Тильде, развиваем соцсети, готовимся к\u00A0выходу на\u00A0новые площадки.",
      project_1_roadmap_1_title: "Архитектура бота",
      project_1_roadmap_1_desc: "Составила CJM и\u00A0логику работы. Разработала проект структуры на\u00A0n8n и\u00A0основных сценариев: подбор косметики, анализ состава, сборка бьюти-бокса.",
      project_1_roadmap_2_title: "Создание бренда",
      project_1_roadmap_2_desc: "Изучила аудиторию и\u00A0ее проблемы. Разрабатывала персонажа по\u00A0принципу «не\u00A0слишком реалистично, но\u00A0и\u00A0не\u00A0безлико»: цепляющий, намеренно мультяшный маскот со\u00A0своей философией.",
      project_1_roadmap_3_title: "AI-интеграция",
      project_1_roadmap_3_desc: "Внедрила DeepSeek и\u00A0Mistral через LLM API. Написала промт для\u00A0агента n8n. Подготовила структуру для\u00A0базы данных.",
      project_1_roadmap_4_title: "Бета-тест",
      project_1_roadmap_4_desc: "Тестировала функционал, собирала обратную связь, дорабатывала CJM. Запуск в\u00A0соцсетях, бартерные коллаборации с\u00A0микро-креаторами, реклама у\u00A0блогеров",
      project_2_title: "Карта «Тройка» в\u00A0регионах",
      project_2_desc: "Развитие «Тройки» как символ локальной идентичности",
      project_2_full: "«Тройка» – давно не\u00A0только московская карта. Она работает в\u00A020+ регионах России, и\u00A0у\u00A0каждого - свой уникальный дизайн карты, отражающий историю, природу и\u00A0культуру места. Процесс создания уникальный «Троек» я лидировала в\u00A0СберТройке с\u00A02023 по\u00A02025 год. **Моя роль** Арт-дирекшн, выстраивание дизайн-процессов, разработка дизайна, иллюстрации.",
      project_2_challenge_1: "Каждый проект создавался почти с\u00A0нуля: нет единых гайдлайнов и\u00A0брифов.",
      project_2_challenge_2: "Задача №1 – объединить потребности компании и\u00A0региона с\u00A0треобованиями акционера-владельца бренда «Тройки».",
      project_2_solution_1: "Решение: выстроила процесс с\u00A0чёткими этапами и\u00A0сроками. Создала единый бриф для\u00A0заказчиков (через «Яндекс Формы»), гайдлайн с\u00A0требованиями к\u00A0дизайну и\u00A0универсальный шаблон презентации в\u00A0Figma.",
      project_2_solution_2: "Результат: время согласования сократилось на\u00A030%, за\u00A0счёт появления четких этапов. Более 70% проектов согласованы с\u00A0первого раза с\u00A0минимальными правками. Более 75 дизайнов карт создано, из\u00A0них более 25 выпущены в\u00A0рамках региональной серии.",
      project_2_roadmap_1_title: "Разработка брифа",
      project_2_roadmap_1_desc: "Онлайн-анкета для\u00A0внешних заказчиков: предпочтения, цветовая гамма, сроки. Заполненный бриф автоматически уходил всем участникам проекта.",
      project_2_roadmap_2_title: "Создание гайдлайна",
      project_2_roadmap_2_desc: "Документ с\u00A0описанием этапов работы, таймлайном требованиями к\u00A0дизайну – выжимка брендбука «Тройки» и\u00A0внутренние правила компании в\u00A0одном месте.",
      project_2_roadmap_3_title: "Исследование",
      project_2_roadmap_3_desc: "Каждый проект начинался с\u00A0погружения в\u00A0регион: традиции, культура, символы. Задача – подчеркнуть ту идентичность, которую сам регион хочет сохранить.",
      project_2_roadmap_4_title: "Дизайн",
      project_2_roadmap_4_desc: "На концептуальном этапе – 3-5 идей, 2-3 уходили в\u00A0детальную отрисовку. На финише – минимум 2 готовых макета в\u00A0Adobe Illustrator или\u00A0Procreate. Средний проект: 2-3 недели.",
      project_3_title: "Система информирования",
      project_3_desc: "Подготовка печатных материалов к\u00A0запуску транспортных проектов стала эффективнее",
      project_3_full: "К билетной системе СберТройки подключено более 17 000 транспортных средств - и\u00A0в\u00A0каждом есть материалы, которые ежедневно видят миллионы пассажиров в\u00A034 регионах. Чтобы обеспечить качество и\u00A0снизить затраты, я создала систему подготовки печатных и\u00A0цифровых материалов. **My role** Арт-дирекшн, выстраивание дизайн-процессов, разработка дизайна.",
      project_3_challenge_1: "Ежегодно печатались десятки тысяч наклеек, листовок и\u00A0памяток – но\u00A0без\u00A0системы.",
      project_3_challenge_2: "Макеты были визуально похожи, однако для\u00A0каждого региона свои, и\u00A0их постоянно перепечатывали, что увеличивало расходы и\u00A0временные затраты.",
      project_3_solution_1: "Решение: базовый пакет материалов, который подходит большинству регионов или\u00A0легко адаптируется. Разработала бриф для\u00A0сбора потребностей и\u00A0гайдлайн с\u00A0описанием видов материалов и\u00A0способов применения.",
      project_3_solution_2: "Результат: Система блоков в\u00A0макетах позволила легко адаптировать материалы под\u00A0любой регион. Количество вариантов стикеров в\u00A0базовом наборе сократилось с\u00A03-5 до\u00A02-3. Выпущено более 10 000 новых материалов.",
      project_3_roadmap_1_title: "Типизация",
      project_3_roadmap_1_desc: "Проанализировала и\u00A0систематизировала существующие макеты, собрала самые востребованные форматы. Провела аудит уже напечатанных материалов, актуализировала информацию с\u00A0региональными менеджерами.",
      project_3_roadmap_2_title: "Бриф и\u00A0гайдлайн",
      project_3_roadmap_2_desc: "Подготовила бриф для\u00A0сбора потребностей и\u00A0сроков для\u00A0внутренних и\u00A0внешних заказчиков (менеджеры и\u00A0регионы). Создала гайдлайн с\u00A0базовым и\u00A0расширенным пакетами, закрывающими 70% запросов.",
      project_4_title: "«Тройка» х Space-π",
      project_4_desc: "Социальный проект и\u00A0карта, вышедшая на\u00A0околоземную орбиту",
      project_4_full: "Карта «Тройка», созданная совместно с\u00A0научно-образовательным проектом Space-π, стала первой транспортной картой, побывавшей на\u00A0орбите. На ней - рисунок победителя детского конкурса, посвященный защите окружающей среды. Создана серия из\u00A05 карт «Тройка», тема: космос глазами детей. **Моя роль** Арт-дирекшн проекта.",
      project_4_challenge_1: "Поднять узнаваемость бренда «Тройки» и\u00A0привлечь внимание к\u00A0образовательному проекту, помогающему школьникам участвовать в\u00A0космических исследованиях.",
      project_4_challenge_2: "Это социальный проект, он реализован на\u00A0благотворительной основе при\u00A0поддержке Фонда содействия инновациям.",
      project_4_solution_1: "Серия карт с\u00A0оцифрованными рисунками финалистов конкурса - о\u00A0космосе и\u00A0защите природы. Главный герой каждой карты - осьминог, маскот Space-π.",
      project_4_solution_2: "Одна из\u00A0карт доставлена на\u00A0орбиту, а\u00A0её изображение было напечатано на\u00A0ракете-носителе.",
      project_5_title: "«Тройка» × Минкульт\u00A0МО",
      project_5_desc: "Развитие культурного туризма и\u00A0рост использования карты «Тройка»",
      project_5_full: "«Путешествуй с\u00A0«Тройкой» по\u00A0Подмосковью» – совместный проект СберТройки и\u00A0Министерства культуры и\u00A0туризма Московской области. Создана лимитированная карта, которую могли получить участники промоакции в\u00A0одном из\u00A0культурных объектов региона. **Моя роль** Арт-дирекшн.",
      project_5_challenge_1: "Цель: рост узнаваемости и\u00A0использования карты «Тройка» в\u00A0Московской области на\u00A0новых маршрутах.",
      project_5_challenge_2: "Задачи: увеличить процент поездок по\u00A0карте и\u00A0способствовать развитию внутреннего туризма Московской области.",
      project_5_solution_1: "Решение: коллаборация с\u00A0Минкультом. Музеи – точка притяжения, «Тройка» – инструмент логистики. В проекте участвовали «Новый Иерусалим», парк Малевича и\u00A0другие.",
      project_5_solution_2: "Результат: акция стартовала в\u00A05 музеях Подмосковья, получила широкое освещение в\u00A0СМИ. За первые две недели – более 500 участников с\u00A0хэштегом Подмосковье_с_Тройкой.",
      project_5_roadmap_1_title: "Концепция и\u00A0дизайн",
      project_5_roadmap_1_desc: "После подбора музеев разработала концепцию дизайна. «Карта на\u00A0карте» – каждый культурный объект становится частью самого макета. В процессе согласования появился новый, минималистичный вариант дизайна, который в\u00A0итоге ушел в\u00A0печать.",
      project_5_roadmap_2_title: "Механика акции",
      project_5_roadmap_2_desc: "Участник приезжает в\u00A0музей, находит на\u00A0территории плакат с\u00A0акцией и\u00A0выполняет главное условие – публикует фото в\u00A0соцсетях. Приз – лимитированная карта «Тройка».",
      project_6_title: "СберТройка × СМФ",
      project_6_desc: "Масштабный проект с\u00A0работой над\u00A0лицензионным продуктом",
      project_6_full: "Коллаборация СберТройки и\u00A0Союзмультфильма. Главные герои серий – персонажи советских мультфильмов, знакомых с\u00A0детства. За время проекта создали 4+ серии карт, более 20 дизайнов, тираж – более 20 000 штук. **Моя роль** Арт-дирекшн, разработка дизайна.",
      project_6_challenge_1: "Работа с\u00A0лицензионными персонажами – это\u00A0строгие гайдлайны и\u00A0несколько кругов строгих согласований.",
      project_6_challenge_2: "Задача: соблюсти все лицензионные и\u00A0технические условия, создав цепляющий, а\u00A0главное, коммерчески успешный дизайн.",
      project_6_solution_1: "Для каждого мультфильма – серия из\u00A04-6 карт с\u00A0единым стилем коллекции. Выпустили серии с\u00A0героями «Карлсона», «Бременских музыкантов», «Ну, погоди!», «Ёжика в\u00A0тумане» и\u00A0др.",
      project_6_solution_2: "Цена карты при\u00A0продаже выросла вдвое за\u00A0счёт уникального дизайна (с\u00A0150 до\u00A0300 рублей за\u00A0штуку.) Солдаут за\u00A0один день в\u00A0точках продаж (киосках «Печать» в\u00A0Москве и\u00A0отделениях Сбера в\u00A0МО, Туле и\u00A0Новосибирске.) Узнаваемость карты в\u00A0этих регионах выросла в\u00A0среднем на\u00A03-6%.",
      project_6_roadmap_1_title: "Исследование",
      project_6_roadmap_1_desc: "Самое любимое за\u00A0всю карьеру: смотрела мультфильмы, выбирала сюжеты и\u00A0ловила характер персонажей. Плюс изучала гайдлайны по\u00A0каждому мультфильму: допустимые связки, позы, элементы.",
      project_6_roadmap_2_title: "Дизайн",
      project_6_roadmap_2_desc: "Главная задача – поместить ярких персонажей в\u00A0маленький формат карты и\u00A0не\u00A0потерять выразительность. Фон и\u00A0декоративные элементы давали пространство для\u00A0собственного взгляда в\u00A0рамках лицензионных ограничений.",
      project_7_title: "СберТройка х ПМЭФ",
      project_7_desc: "Эксклюзивные альбомы стейкхолдеров и\u00A0vip-гостей форума",
      project_7_full: "Альбом с\u00A0лимитированной серией транспортных карт – промо компании на\u00A0ПМЭФ и\u00A0желанный подарок для\u00A0гостей форума. Не просто сувенир – переосмысление корпоративного мерча. Разработала два альбома: 2023 и\u00A02025 года, каждый со\u00A0своей концепцией. **Моя роль** Создание концепции, разработка дизайна.",
      project_7_challenge_1: "Задача – сделать не\u00A0просто красивый сувенир, а\u00A0объект, который расскажет о\u00A0технологическом развитии компании и\u00A0не\u00A0окажется в\u00A0ящике стола. Аудитория – главы регионов и\u00A0ключевые партнёры.",
      project_7_solution_1: "Решение: альбом как история: каждый – новая глава в\u00A0развитии компании, рассказанная через транспортные карты. «Тройка» стала связующим звеном между московским и\u00A0региональным транспортом.",
      project_7_solution_2: "Результат: первый тираж – 50 экземпляров, второй – 100. Оба представлены на\u00A0стенде Московского транспорта, подарены ключевым партнёрам и\u00A0главам регионов. Альбом стал самостоятельным инфоповодом – с\u00A0отдельными выходами в\u00A0СМИ.",
      project_7_roadmap_1_title: "Первый альбом (2023)",
      project_7_roadmap_1_desc: "Тема – транспорт будущего, в\u00A0коллаборации с\u00A0нейросетью Kandinsky 2.1. «Тройка» под\u00A0землёй, на\u00A0земле, на\u00A0воде и\u00A0в\u00A0воздухе. Параллельно – анонс приложения «Моя Тройка»: дизайны из\u00A0альбома можно было выпустить как виртуальную карту.",
      project_7_roadmap_2_title: "Второй альбом (2025)",
      project_7_roadmap_2_desc: "Акцент на\u00A0выход «Тройки» в\u00A0регионы. Серия прозрачных карт, посвящённых крупнейшим подключённым регионам. Специальная конструкция альбома со\u00A0встроенными светодиодами - карты буквально светились изнутри.",
      project_8_title: "Транспортная реформа НСО",
      project_8_desc: "Масштабный запуск проекта в\u00A0Новосибирсклй области",
      project_8_full: "В 2025 году СберТройка запустила масштабный транспортный проект в\u00A0Новосибирске. Итог: более 200 макетов, более 90 000 напечатанных материалов, 90% городского транспорта и\u00A0социальных объектов оснащено. **Моя роль** Полное дизайн-сопровождение проекта, лидирование дизайн-процессов.",
      project_8_challenge_1: "Задача: рассказать горожанам о\u00A0переходе на\u00A0новую билетную систему. Информирование должно было стать максимально понятным и\u00A0последовательным руководством для\u00A0всех категорий пассажиров. Разработка новых форматов и\u00A0огромном тираже, не\u00A0только для\u00A0транспорта, но\u00A0и\u00A0для\u00A0школ, университетов, отделений банков и\u00A0т.д. ",
      project_8_solution_1: "Решение: несколько волн информационной кампании: карточки для\u00A0соцсетей, инструкции для\u00A0сайта, листовки, плакаты для\u00A0госучреждений, объявления в\u00A0транспорте. Материалы разделены дизайном, цветом и\u00A0типом контента для\u00A0разных аудиторий (школьники, студенты, пенсионеры, и\u00A0обычные пассажиры).", 
      project_8_solution_2: "Результат: Более 15 пользовательских инструкций, более 30 новых форматов печатных материалов, более 20 дизайнов транспортных карт. Также: навигация для\u00A0Центров обслуживания населения, дизайн рабочих мест и\u00A0униформы сотрудников.", 
      project_8_roadmap_1_title: "Подготовка",
      project_8_roadmap_1_desc: "Отдельная стилистика, страница на\u00A0сайте и\u00A0Telegram-канал для\u00A0ежедневных обновлений. Обновлённые дизайны социальных карт, создание инфографик и\u00A0инструкций по\u00A0переходу на\u00A0новую систему для\u00A0каждой категории пользователей.",
      project_8_roadmap_2_title: "Оптимизация печати",
      project_8_roadmap_2_desc: "Решила проблему большого тиража через работу с\u00A0текстом и\u00A0систему универсальных блоков: сократила объём примерно на\u00A040% - затраты на\u00A0печать снизились на\u00A020% без\u00A0потери информативности.",
      project_9_title: "Книга «Я\u00A0рисую\u00A0море»",
      project_9_desc: "Дипломный проект стал полноценным изданием для\u00A0детей",
      project_9_full: "«Я рисую море» – издание, посвященное 90-летию детского поэта Владимира Орлова. Цель – популяризировать творчество автора среди современных детей. В книге – иллюстрированные стихи и\u00A0игровые элементы для\u00A0развития дошкольников. **Моя роль** Концепция издания, иллюстрации, книжная вёрстка, разработка заданий.",
      project_9_challenge_1: "Проект был дипломной работой, поэтому прежде всего – свежий взгляд на\u00A0тему и\u00A0нестандартный подход.",
      project_9_challenge_2: "Требовалось создать издание с\u00A0уникальной концепцией, реально полезное для\u00A0аудитории и\u00A0достойное публикации за\u00A0пределами вуза.",      
      project_9_solution_1: "Решение: интерактивный сборник с\u00A0атмосферой летнего морского путешествия. Каждый разворот – стихотворение, иллюстрация и\u00A0клапан с\u00A0развивающим заданием. ",
      project_9_solution_2: "Результат: книга издана за\u00A0счёт грант Министерства культуры Республики Крым, тираж 1000 экземпляров. Распространена по\u00A0библиотекам Крыма и\u00A0соседних регионов, часть тиража передана в\u00A0детские дома и\u00A0интернаты.",
      project_9_roadmap_1_title: "Концепция",
      project_9_roadmap_1_desc: "Владимира Орлова называют «крымским Маршаком» – его творчество связано с\u00A0лагерем «Артек» и\u00A0Крымом. Отсюда концепция: летнее путешествие по\u00A0Крыму.",
      project_9_roadmap_2_title: "Оформление книги",
      project_9_roadmap_2_desc: "Иллюстрации отрисованы в\u00A0Adobe Photoshop, вёрстка – в\u00A0Adobe InDesign. Легкий декоративный стиль выбран чтобы подчеркнуть настроение стихов. Цветовая гамма меняется вместе с\u00A0временем суток – рассветные тона в\u00A0начале, яркий день в\u00A0середине, приглушённые вечерние краски в\u00A0конце.",
      project_9_roadmap_3_title: "Конструкция",
      project_9_roadmap_3_desc: "14 разворотов с\u00A0произведениями и\u00A0клапаном, внутри которого спрятаны развивающие задания. Игровые элементы разработаны с\u00A0консультацией специалистов по\u00A0развитию дошкольников.",
      challenges_title: "Ключевые вызовы & Цели",
      solution_title: "Решение & Результат",
      projectroadmap_title: "Путь проекта",
      tools_title: "Инструменты & технологии",
      view_project: "Подробнее",
    },
  contact: {
    title: "Давайте работать вместе",
    subtitle: "Есть проект? Нужна AI-интеграция или\u00A0помощь с\u00A0проектом? Давайте обсудим.",
    get_in_touch: "Связаться",
    email: "Email",
    phone: "Телефон",
    location: "Местоположение",
    location_city: "Москва",
    location_country: "Россия",
    response_time: "Время ответа",
    response_desc: "Обычно я отвечаю в\u00A0течение 24 часов. Для срочных проектов, пожалуйста, укажите это\u00A0в\u00A0сообщении.",
    name: "Имя",
    name_placeholder: "Ваше имя",
    email_placeholder: "your.email@example.com",
    subject: "Тема",
    subject_placeholder: "О чем речь?",
    message: "Сообщение",
    message_placeholder: "Расскажите о\u00A0вашем проекте...",
    send_message: "Отправить сообщение",
    thank_you: "Спасибо!",
    success_message: "Ваше сообщение отправлено. Я свяжусь с\u00A0вами в\u00A0ближайшее время!",
  },
  footer: {
    tagline: "Digital Producer и\u00A0AI-креатор — создаю продукты, которые работают.",
    quick_links: "Быстрые ссылки",
    connect: "Контакты",
    copyright: "© 2026 Яна Пойманова. Все права защищены.",
  },
  },
};
